Repository redhat-beyond/lets-meet, pull requests merged in 2022-05, with the labels that each got.

#72 Reminder form
  events/class_tests/possible_participant_tests.py
  events/static/events/create_event.css
  events/static/reminders/reminder_form.css
  events/static/reminders/reminder_form.js
  events/templates/events/create_event.html
  events/views.py
  main/utilities.py
  reminders/class_tests/create_reminder_tests.py
  reminders/class_tests/reminders_tests.py
  reminders/class_tests/update_reminder_tests.py
  reminders/conftest.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0003_alter_reminder_method.py
  reminders/models.py
  reminders/scheduler.py
  reminders/tests.py
  users/static/update_profile/update_form.css
  users/static/user_site/home.css
  users/templates/user_site/home.html
  users/views.py
Labels: enhancement, ready to merge

#73 Notification
  main/utilities.py
  reminders/admin.py
  reminders/class_models/__init__.py
  reminders/class_models/notification_models.py
  reminders/class_models/reminder_models.py
  reminders/class_tests/__init__.py
  reminders/class_tests/notification_tests.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0003_add_notification_test_data.py
  reminders/models.py
  reminders/scheduler.py
Labels: enhancement, ready to merge

#80 Creating basic file form
  eventfiles/class_tests/__init__.py
  eventfiles/class_tests/event_file_tests.py
  eventfiles/class_tests/event_file_views_tests.py
  eventfiles/form.py
  eventfiles/migrations/0001_initial.py
  eventfiles/models.py
  eventfiles/static/event_files/event_files.css
  eventfiles/static/event_files/event_files.js
  eventfiles/templates/file/event_files.html
  eventfiles/tests.py
  eventfiles/urls.py
  eventfiles/views.py
  events/static/events/create_event.css
  events/static/reminders/reminder_form.css
  events/templates/events/create_event.html
  events/urls.py
  events/views.py
  lets_meet/urls.py
  users/templates/user_site/home.html
Labels: enhancement, ready to merge

#74 Site notification
  lets_meet/urls.py
  main/utilities.py
  reminders/class_models/notification_models.py
  reminders/class_models/reminder_models.py
  reminders/class_tests/notification_tests.py
  reminders/class_tests/reminders_tests.py
  reminders/conftest.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0003_add_notification_test_data.py
  reminders/tests.py
  reminders/urls.py
  reminders/views.py
  users/static/site_notification/notification.css
  users/static/site_notification/notification.js
  users/static/user_site/home.css
  users/static/user_site/home.js
  users/templates/user_site/home.html
Labels: enhancement, ready to merge

#84 Create meeting forms and views
  events/class_models/meeting_models.py
  events/class_models/possible_participant_model.py
  events/class_tests/meeting_tests.py
  events/forms.py
  events/migrations/0005_optionalmeetingdates.py
  events/static/events/create_event.css
  events/static/meetings/create_meeting.css
  events/static/meetings/create_meeting.js
  events/templates/meetings/create_meeting.html
  events/urls.py
  events/views.py
  users/templates/user_site/home.html
Labels: enhancement, ready to merge

#87 Adding meeting algorithm
  events/class_models/possible_participant_model.py
  events/class_tests/planner_tests.py
  events/class_tests/possible_participant_tests.py
  events/migrations/0008_add_possible_participant_test_data.py
  events/planner.py
  events/tests.py
Labels: enhancement, ready to merge

#91 Test for meeting form
  events/class_tests/create_events.py
  events/class_tests/create_meeting_form.py
  events/tests.py
Labels: Status/New, enhancement

#93 Advanced algorithm
  events/class_models/participant_model.py
  events/class_models/possible_participant_model.py
  events/class_tests/create_meeting_form.py
  events/class_tests/event_tests.py
  events/class_tests/planner_tests.py
  events/class_tests/possible_participant_tests.py
  events/forms.py
  events/migrations/0002_event_test_data.py
  events/migrations/0004_add_event_participant_test_data.py
  events/migrations/0006_add_possible_meeting_test_data.py
  events/migrations/0008_add_possible_participant_test_data.py
  events/planner.py
  events/templates/events/create_event.html
  events/views.py
  main/utilities.py
  reminders/class_models/reminder_models.py
  reminders/class_tests/reminders_tests.py
  reminders/forms.py
  reminders/migrations/0001_initial.py
  reminders/scheduler.py
  users/templates/user_site/home.html
Labels: Status/New, enhancement, ready to merge

#89 Delete option for file
  eventfiles/class_tests/event_file_views_tests.py
  eventfiles/static/event_files/delete_pop_up.css
  eventfiles/static/event_files/event_files.css
  eventfiles/static/event_files/event_files.js
  eventfiles/templates/file/event_files.html
  eventfiles/urls.py
  eventfiles/views.py
  events/class_models/participant_model.py
Labels: enhancement, ready to merge

#96 Invitation
  events/class_tests/meeting_vote_tests.py
  events/conftest.py
  events/forms.py
  events/migrations/0004_add_event_participant_test_data.py
  events/planner.py
  events/static/events/create_event.css
  events/static/vote/meeting_vote.css
  events/templates/events/create_event.html
  events/templates/vote/meeting_vote.html
  events/templatetags/__init__.py
  events/templatetags/events_extras.py
  events/urls.py
  events/views.py
  main/utilities.py
  reminders/class_models/notification_models.py
  reminders/class_tests/notification_tests.py
  reminders/class_tests/users_notification_tests.py
  reminders/conftest.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0003_add_notification_test_data.py
  reminders/views.py
  users/static/site_notification/notification.js
  users/templates/base.html
  users/templates/user_site/home.html
Labels: enhancement, ready to merge

#100 Google
  Pipfile
  Pipfile.lock
  events/static/events/create_event.css
  events/static/meetings/create_meeting.css
  events/templates/meetings/create_meeting.html
  events/views.py
  lets_meet/.env
  lets_meet/settings.py
  lets_meet/urls.py
  main/migrations/0001_update_site_name.py
  main/migrations/0002_add_google_account.py
  users/static/base.css
  users/static/login/login.css
  users/static/site_notification/notification.css
  users/static/site_notification/notification.js
  users/static/update_profile/update_form.css
  users/static/user_site/home.css
  users/templates/login/register_login.html
  users/templates/update_profile/update_form.html
  users/templates/user_site/home.html
Labels: Status/New, enhancement, ready to merge
