Repository redhat-beyond/lets-meet, pull requests merged in 2022-04, with the labels that each got.

#32 Participants model
  events/admin.py
  events/migrations/0002_event_test_data.py
  events/migrations/0003_eventparticipant.py
  events/migrations/0004_add_event_participant_test_data.py
  events/models.py
  events/tests.py
Labels: ready to merge

#38 Possible meeting model
  events/admin.py
  events/migrations/0005_possiblemeeting.py
  events/migrations/0006_add_possible_meeting_test_data.py
  events/models.py
  events/tests.py
  lets_meet/settings.py
Labels: ready to merge

#46 Fixing user test
  users/tests.py
Labels: ready to merge

#39 adding reminders model and tests.
  lets_meet/settings.py
  reminders/__init__.py
  reminders/admin.py
  reminders/apps.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0002_add_reminder_test_data.py
  reminders/migrations/__init__.py
  reminders/models.py
  reminders/tests.py
  reminders/views.py
Labels: ready to merge

#42 Adding Event File Module
  eventfiles/__init__.py
  eventfiles/admin.py
  eventfiles/apps.py
  eventfiles/migrations/0001_initial.py
  eventfiles/migrations/0002_add_events_files_test_data.py
  eventfiles/migrations/__init__.py
  eventfiles/models.py
  eventfiles/tests.py
  eventfiles/views.py
  lets_meet/settings.py
  static/test_files/testFile.txt
  static/test_files/testFile1.txt
  static/test_files/testFile2.txt
  static/test_files/testFile3.txt
  users/migrations/0001_initial.py
  users/models.py
  users/tests.py
Labels: ready to merge

#40 Arrange models
  events/class_models/__init__.py
  events/class_models/event_models.py
  events/class_models/meeting_models.py
  events/class_models/participant_model.py
  events/class_tests/__init__.py
  events/class_tests/event_tests.py
  events/class_tests/meeting_tests.py
  events/class_tests/participant_test.py
  events/models.py
  events/tests.py
Labels: ready to merge

#52 Login And Register Pages :computer:
  bootstrap.sh
  eventfiles/tests.py
  events/class_tests/event_tests.py
  events/class_tests/meeting_tests.py
  events/class_tests/participant_test.py
  lets_meet/settings.py
  lets_meet/urls.py
  main/templates/main/index.html
  reminders/tests.py
  users/class_tests/__init__.py
  users/class_tests/constants.py
  users/class_tests/login_tests.py
  users/class_tests/logout_tests.py
  users/class_tests/sign_up_tests.py
  users/class_tests/users_tests.py
  users/forms.py
  users/migrations/0002_add_user_test_data.py
  users/models.py
  users/static/base.css
  users/static/login/login.css
  users/static/login/login.js
  users/static/user_site/home.css
  users/static/user_site/home.js
  users/templates/base.html
  users/templates/login/register_login.html
  users/templates/user_site/home.html
  users/tests.py
  users/urls.py
  users/views.py
Labels: enhancement, ready to merge

#55 User Alert Scheduler
  .bashrc
  .gitignore
  Pipfile
  Pipfile.lock
  Vagrantfile
  lets_meet/.env
  lets_meet/settings.py
  main/utilities.py
  reminders/apps.py
  reminders/migrations/0001_initial.py
  reminders/migrations/0003_alter_reminder_method.py
  reminders/models.py
  reminders/scheduler.py
  reminders/tests.py
Labels: Status/New, enhancement, ready to merge

#57 Add create event page
  events/class_models/event_models.py
  events/class_tests/create_events.py
  events/forms.py
  events/static/events/create_event.css
  events/templates/events/create_event.html
  events/tests.py
  events/urls.py
  events/views.py
  lets_meet/urls.py
  reminders/forms.py
  users/class_tests/users_tests.py
  users/templates/user_site/home.html
Labels: ready to merge

#66 Main site
  users/forms.py
  users/static/update_profile/update_form.css
  users/static/user_site/home.css
  users/templates/base.html
  users/templates/update_profile/update_form.html
  users/templates/user_site/home.html
  users/urls.py
  users/views.py
Labels: enhancement, ready to merge

#63 Add query set and tests to Event Participant model
  eventfiles/migrations/0001_initial.py
  eventfiles/models.py
  events/admin.py
  events/class_models/meeting_models.py
  events/class_models/participant_model.py
  events/class_models/possible_participant_model.py
  events/class_tests/event_tests.py
  events/class_tests/meeting_tests.py
  events/class_tests/participant_test.py
  events/class_tests/possible_participant_tests.py
  events/migrations/0005_optionalmeetingdates.py
  events/migrations/0006_add_possible_meeting_test_data.py
  events/migrations/0007_possibleparticipant.py
  events/migrations/0008_add_possible_participant_test_data.py
  reminders/migrations/0001_initial.py
Labels: ready to merge
